export const producrtsSeed = [
  {
    ProductID: 1,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Classic Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, fresh cucumber, fresh tomato, garlic sauce, chicken',
    UnitPrice: 7.5,
    SmallImage: '01.jpeg',
    BigImage: '01.jpeg',
  },
  {
    ProductID: 2,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Classic Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, fresh cucumber, fresh tomato, garlic sauce, chicken',
    UnitPrice: 9,
    SmallImage: '01.jpeg',
    BigImage: '01.jpeg',
  },
  {
    ProductID: 3,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Classic Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, fresh cucumber, fresh tomato, garlic sauce, chicken',
    UnitPrice: 12,
    SmallImage: '01.jpeg',
    BigImage: '01.jpeg',
  },
  {
    ProductID: 4,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Piquant Small (300 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, pickled cucumber, spicy carrot, spicy sauce, chicken',
    UnitPrice: 7.5,
    SmallImage: '02.jpeg',
    BigImage: '02.jpeg',
  },
  {
    ProductID: 5,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Piquant Medium (420 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, pickled cucumber, spicy carrot, spicy sauce, chicken',
    UnitPrice: 9,
    SmallImage: '02.jpeg',
    BigImage: '02.jpeg',
  },
  {
    ProductID: 6,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Piquant Large (600 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, pickled cucumber, spicy carrot, spicy sauce, chicken',
    UnitPrice: 12,
    SmallImage: '02.jpeg',
    BigImage: '02.jpeg',
  },
  {
    ProductID: 7,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Spicy Small (300 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh tomato, chicken, mustard sauce, bacon',
    UnitPrice: 7.5,
    SmallImage: '03.jpeg',
    BigImage: '03.jpeg',
  },
  {
    ProductID: 8,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Spicy Medium (420 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh tomato, chicken, mustard sauce, bacon',
    UnitPrice: 9,
    SmallImage: '03.jpeg',
    BigImage: '03.jpeg',
  },
  {
    ProductID: 9,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Spicy Large (600 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh tomato, chicken, mustard sauce, bacon',
    UnitPrice: 12,
    SmallImage: '03.jpeg',
    BigImage: '03.jpeg',
  },
  {
    ProductID: 10,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Cheese Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh cucumber, fresh tomato, cheese, cheese sauce, chicken',
    UnitPrice: 7.5,
    SmallImage: '04.jpeg',
    BigImage: '04.jpeg',
  },
  {
    ProductID: 11,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Cheese Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh cucumber, fresh tomato, cheese, cheese sauce, chicken',
    UnitPrice: 9,
    SmallImage: '04.jpeg',
    BigImage: '04.jpeg',
  },
  {
    ProductID: 12,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Cheese Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh cucumber, fresh tomato, cheese, cheese sauce, chicken',
    UnitPrice: 12,
    SmallImage: '04.jpeg',
    BigImage: '04.jpeg',
  },
  {
    ProductID: 13,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Teriyaki Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh cucumber, chicken, sesame, teriyaki sauce',
    UnitPrice: 7.5,
    SmallImage: '05.jpeg',
    BigImage: '05.jpeg',
  },
  {
    ProductID: 14,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Teriyaki Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh cucumber, chicken, sesame, teriyaki sauce',
    UnitPrice: 9,
    SmallImage: '05.jpeg',
    BigImage: '05.jpeg',
  },
  {
    ProductID: 15,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Teriyaki Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh cucumber, chicken, sesame, teriyaki sauce',
    UnitPrice: 12,
    SmallImage: '05.jpeg',
    BigImage: '05.jpeg',
  },
  {
    ProductID: 16,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Mediterranean Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, Iceberg lettuce, pesto sauce, fresh cucumber, fresh tomato, chicken, garlic sauce',
    UnitPrice: 8,
    SmallImage: '06.jpeg',
    BigImage: '06.jpeg',
  },
  {
    ProductID: 17,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Mediterranean Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, Iceberg lettuce, pesto sauce, fresh cucumber, fresh tomato, chicken, garlic sauce',
    UnitPrice: 18,
    SmallImage: '06.jpeg',
    BigImage: '06.jpeg',
  },
  {
    ProductID: 18,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Mediterranean Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, Iceberg lettuce, pesto sauce, fresh cucumber, fresh tomato, chicken, garlic sauce',
    UnitPrice: 13,
    SmallImage: '06.jpeg',
    BigImage: '06.jpeg',
  },
  {
    ProductID: 19,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Hunting Small (300 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh tomato, onion, chicken, smoked sausages, hunting sauce',
    UnitPrice: 8,
    SmallImage: '07.jpeg',
    BigImage: '07.jpeg',
  },
  {
    ProductID: 20,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Hunting Medium (420 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh tomato, onion, chicken, smoked sausages, hunting sauce',
    UnitPrice: 10,
    SmallImage: '07.jpeg',
    BigImage: '07.jpeg',
  },
  {
    ProductID: 21,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Hunting Large (600 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh tomato, onion, chicken, smoked sausages, hunting sauce',
    UnitPrice: 13,
    SmallImage: '07.jpeg',
    BigImage: '07.jpeg',
  },
  {
    ProductID: 22,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Ranch Small (300 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Lavash, Ranch sauce, Iceberg lettuce, fresh cucumber, fresh tomato, cheese',
    UnitPrice: 7.5,
    SmallImage: '08.jpeg',
    BigImage: '08.jpeg',
  },
  {
    ProductID: 23,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Ranch Medium (420 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Lavash, Ranch sauce, Iceberg lettuce, fresh cucumber, fresh tomato, cheese',
    UnitPrice: 9,
    SmallImage: '08.jpeg',
    BigImage: '08.jpeg',
  },
  {
    ProductID: 24,
    ProductType: 'food',
    ProductTitle: 'Shawarma',
    ProductSubtitle: 'Ranch Large (600 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Lavash, Ranch sauce, Iceberg lettuce, fresh cucumber, fresh tomato, cheese',
    UnitPrice: 12,
    SmallImage: '08.jpeg',
    BigImage: '08.jpeg',
  },
  {
    ProductID: 25,
    ProductType: 'food',
    ProductTitle: 'Burger',
    ProductSubtitle: 'Ranch (320 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Burger bun, Iceberg lettuce, fresh tomato, pickled cucumber, mustard sauce, ranch sauce, beef patty, cheddar cheese',
    UnitPrice: 7.5,
    SmallImage: '09.jpeg',
    BigImage: '09.jpeg',
  },
  {
    ProductID: 26,
    ProductType: 'drink',
    ProductTitle: 'Mirinda',
    ProductSubtitle: '500 ml',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription: '',
    UnitPrice: 1.6,
    SmallImage: '10.jpeg',
    BigImage: '',
  },
  {
    ProductID: 27,
    ProductType: 'drink',
    ProductTitle: '7Up',
    ProductSubtitle: '500 ml',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription: '',
    UnitPrice: 1.6,
    SmallImage: '11.jpeg',
    BigImage: '',
  },
  {
    ProductID: 28,
    ProductType: 'food',
    ProductTitle: 'Rice',
    ProductSubtitle: 'Rice with vegetables (300/3 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Rice with vegetables stewed in tom yam broth: rice, zucchini, leek, carrot, pepper, broccoli, soy sauce, garlic, tom yam broth, sesame, green onion',
    UnitPrice: 12.9,
    SmallImage: '12.jpeg',
    BigImage: '12.jpeg',
  },
  {
    ProductID: 29,
    ProductType: 'food',
    ProductTitle: 'Green Mix',
    ProductSubtitle: '130 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Green mix with avocado, tomatoes and pumpkin seeds: salad mix, avocado, dried tomatoes, cherry, mitsukan sauce with ginger, pumpkin seeds',
    UnitPrice: 10.9,
    SmallImage: '13.jpeg',
    BigImage: '13.jpeg',
  },
  {
    ProductID: 30,
    ProductType: 'food',
    ProductTitle: 'Penne',
    ProductSubtitle: '300/5 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Penne with vegetable mix and roasted hazelnuts: penne, pepper, carrot, cucumber, canned beans, garlic, parsley, hazelnuts, mitsukan sauce with ginger',
    UnitPrice: 13.5,
    SmallImage: '14.jpeg',
    BigImage: '14.jpeg',
  },
  {
    ProductID: 31,
    ProductType: 'food',
    ProductTitle: 'Hummus',
    ProductSubtitle: '180/85 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Hummus with baked pepper and eggplant: hummus, focaccia, pepper, eggplant',
    UnitPrice: 10.3,
    SmallImage: '15.jpeg',
    BigImage: '15.jpeg',
  },
];
