export const producrtsSeed = [
  {
    ProductID: 1,
    ProductType: 'food',
    ProductName: 'Shawarma Classic',
    ProductWeight: 'Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, fresh cucumber, fresh tomato, garlic sauce, chicken',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/01',
    BigImagePath: './images/goods/big/01',
  },
  {
    ProductID: 2,
    ProductType: 'food',
    ProductName: 'Shawarma Classic',
    ProductWeight: 'Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, fresh cucumber, fresh tomato, garlic sauce, chicken',
    UnitPrice: 9,
    SmallImagePath: './images/goods/small/01',
    BigImagePath: './images/goods/big/01',
  },
  {
    ProductID: 3,
    ProductType: 'food',
    ProductName: 'Shawarma Classic',
    ProductWeight: 'Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, fresh cucumber, fresh tomato, garlic sauce, chicken',
    UnitPrice: 12,
    SmallImagePath: './images/goods/small/01',
    BigImagePath: './images/goods/big/01',
  },
  {
    ProductID: 4,
    ProductType: 'food',
    ProductName: 'Shawarma Piquant',
    ProductWeight: 'Small (300 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, pickled cucumber, spicy carrot, spicy sauce, chicken',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/02',
    BigImagePath: './images/goods/big/02',
  },
  {
    ProductID: 5,
    ProductType: 'food',
    ProductName: 'Shawarma Piquant',
    ProductWeight: 'Medium (420 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, pickled cucumber, spicy carrot, spicy sauce, chicken',
    UnitPrice: 9,
    SmallImagePath: './images/goods/small/02',
    BigImagePath: './images/goods/big/02',
  },
  {
    ProductID: 6,
    ProductType: 'food',
    ProductName: 'Shawarma Piquant',
    ProductWeight: 'Large (600 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, pickled cucumber, spicy carrot, spicy sauce, chicken',
    UnitPrice: 12,
    SmallImagePath: './images/goods/small/02',
    BigImagePath: './images/goods/big/02',
  },
  {
    ProductID: 7,
    ProductType: 'food',
    ProductName: 'Shawarma Spicy',
    ProductWeight: 'Small (300 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh tomato, chicken, mustard sauce, bacon',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/03',
    BigImagePath: './images/goods/big/03',
  },
  {
    ProductID: 8,
    ProductType: 'food',
    ProductName: 'Shawarma Spicy',
    ProductWeight: 'Medium (420 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh tomato, chicken, mustard sauce, bacon',
    UnitPrice: 9,
    SmallImagePath: './images/goods/small/03',
    BigImagePath: './images/goods/big/03',
  },
  {
    ProductID: 9,
    ProductType: 'food',
    ProductName: 'Shawarma Spicy',
    ProductWeight: 'Large (600 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh tomato, chicken, mustard sauce, bacon',
    UnitPrice: 12,
    SmallImagePath: './images/goods/small/03',
    BigImagePath: './images/goods/big/03',
  },
  {
    ProductID: 10,
    ProductType: 'food',
    ProductName: 'Cheese shawarma',
    ProductWeight: 'Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh cucumber, fresh tomato, cheese, cheese sauce, chicken',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/04',
    BigImagePath: './images/goods/big/04',
  },
  {
    ProductID: 11,
    ProductType: 'food',
    ProductName: 'Cheese shawarma',
    ProductWeight: 'Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh cucumber, fresh tomato, cheese, cheese sauce, chicken',
    UnitPrice: 9,
    SmallImagePath: './images/goods/small/04',
    BigImagePath: './images/goods/big/04',
  },
  {
    ProductID: 12,
    ProductType: 'food',
    ProductName: 'Cheese shawarma',
    ProductWeight: 'Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh cucumber, fresh tomato, cheese, cheese sauce, chicken',
    UnitPrice: 12,
    SmallImagePath: './images/goods/small/04',
    BigImagePath: './images/goods/big/04',
  },
  {
    ProductID: 13,
    ProductType: 'food',
    ProductName: 'Shawarma Teriyaki',
    ProductWeight: 'Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh cucumber, chicken, sesame, teriyaki sauce',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/05',
    BigImagePath: './images/goods/big/05',
  },
  {
    ProductID: 14,
    ProductType: 'food',
    ProductName: 'Shawarma Teriyaki',
    ProductWeight: 'Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh cucumber, chicken, sesame, teriyaki sauce',
    UnitPrice: 9,
    SmallImagePath: './images/goods/small/05',
    BigImagePath: './images/goods/big/05',
  },
  {
    ProductID: 15,
    ProductType: 'food',
    ProductName: 'Shawarma Teriyaki',
    ProductWeight: 'Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, garlic sauce, cabbage, fresh cucumber, chicken, sesame, teriyaki sauce',
    UnitPrice: 12,
    SmallImagePath: './images/goods/small/05',
    BigImagePath: './images/goods/big/05',
  },
  {
    ProductID: 16,
    ProductType: 'food',
    ProductName: 'Mediterranean Shawarma',
    ProductWeight: 'Small (300 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, Iceberg lettuce, pesto sauce, fresh cucumber, fresh tomato, chicken, garlic sauce',
    UnitPrice: 8,
    SmallImagePath: './images/goods/small/06',
    BigImagePath: './images/goods/big/06',
  },
  {
    ProductID: 17,
    ProductType: 'food',
    ProductName: 'Mediterranean Shawarma',
    ProductWeight: 'Medium (420 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, Iceberg lettuce, pesto sauce, fresh cucumber, fresh tomato, chicken, garlic sauce',
    UnitPrice: 18,
    SmallImagePath: './images/goods/small/06',
    BigImagePath: './images/goods/big/06',
  },
  {
    ProductID: 18,
    ProductType: 'food',
    ProductName: 'Mediterranean Shawarma',
    ProductWeight: 'Large (600 g)',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Lavash, Iceberg lettuce, pesto sauce, fresh cucumber, fresh tomato, chicken, garlic sauce',
    UnitPrice: 13,
    SmallImagePath: './images/goods/small/06',
    BigImagePath: './images/goods/big/06',
  },
  {
    ProductID: 19,
    ProductType: 'food',
    ProductName: 'Shawarma Hunting',
    ProductWeight: 'Small (300 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh tomato, onion, chicken, smoked sausages, hunting sauce',
    UnitPrice: 8,
    SmallImagePath: './images/goods/small/07',
    BigImagePath: './images/goods/big/07',
  },
  {
    ProductID: 20,
    ProductType: 'food',
    ProductName: 'Shawarma Hunting',
    ProductWeight: 'Medium (420 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh tomato, onion, chicken, smoked sausages, hunting sauce',
    UnitPrice: 10,
    SmallImagePath: './images/goods/small/07',
    BigImagePath: './images/goods/big/07',
  },
  {
    ProductID: 21,
    ProductType: 'food',
    ProductName: 'Shawarma Hunting',
    ProductWeight: 'Large (600 g)',
    isSpicy: true,
    isVegetarian: false,
    ProductDescription:
      'Lavash, cabbage, garlic sauce, fresh tomato, onion, chicken, smoked sausages, hunting sauce',
    UnitPrice: 13,
    SmallImagePath: './images/goods/small/07',
    BigImagePath: './images/goods/big/07',
  },
  {
    ProductID: 22,
    ProductType: 'food',
    ProductName: 'Shawarma Ranch',
    ProductWeight: 'Small (300 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Lavash, Ranch sauce, Iceberg lettuce, fresh cucumber, fresh tomato, cheese',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/08',
    BigImagePath: './images/goods/big/08',
  },
  {
    ProductID: 23,
    ProductType: 'food',
    ProductName: 'Shawarma Ranch',
    ProductWeight: 'Medium (420 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Lavash, Ranch sauce, Iceberg lettuce, fresh cucumber, fresh tomato, cheese',
    UnitPrice: 9,
    SmallImagePath: './images/goods/small/08',
    BigImagePath: './images/goods/big/08',
  },
  {
    ProductID: 24,
    ProductType: 'food',
    ProductName: 'Shawarma Ranch',
    ProductWeight: 'Large (600 g)',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Lavash, Ranch sauce, Iceberg lettuce, fresh cucumber, fresh tomato, cheese',
    UnitPrice: 12,
    SmallImagePath: './images/goods/small/08',
    BigImagePath: './images/goods/big/08',
  },
  {
    ProductID: 25,
    ProductType: 'food',
    ProductName: 'Burger Ranch',
    ProductWeight: '320 g',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription:
      'Burger bun, Iceberg lettuce, fresh tomato, pickled cucumber, mustard sauce, ranch sauce, beef patty, cheddar cheese',
    UnitPrice: 7.5,
    SmallImagePath: './images/goods/small/09',
    BigImagePath: './images/goods/big/09',
  },
  {
    ProductID: 26,
    ProductType: 'drink',
    ProductName: 'Mirinda',
    ProductWeight: '500 ml',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription: '',
    UnitPrice: 1.6,
    SmallImagePath: './images/goods/small/10',
    BigImagePath: '',
  },
  {
    ProductID: 27,
    ProductType: 'drink',
    ProductName: '7Up',
    ProductWeight: '500 ml',
    isSpicy: false,
    isVegetarian: false,
    ProductDescription: '',
    UnitPrice: 1.6,
    SmallImagePath: './images/goods/small/11',
    BigImagePath: '',
  },
  {
    ProductID: 28,
    ProductType: 'food',
    ProductName: 'Rice with vegetables',
    ProductWeight: '300/3 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Rice with vegetables stewed in tom yam broth: rice, zucchini, leek, carrot, pepper, broccoli, soy sauce, garlic, tom yam broth, sesame, green onion',
    UnitPrice: 12.9,
    SmallImagePath: './images/goods/small/12',
    BigImagePath: './images/goods/big/12',
  },
  {
    ProductID: 29,
    ProductType: 'food',
    ProductName: 'Green Mix',
    ProductWeight: '130 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Green mix with avocado, tomatoes and pumpkin seeds: salad mix, avocado, dried tomatoes, cherry, mitsukan sauce with ginger, pumpkin seeds',
    UnitPrice: 10.9,
    SmallImagePath: './images/goods/small/13',
    BigImagePath: './images/goods/big/13',
  },
  {
    ProductID: 30,
    ProductType: 'food',
    ProductName: 'Penne',
    ProductWeight: '300/5 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Penne with vegetable mix and roasted hazelnuts: penne, pepper, carrot, cucumber, canned beans, garlic, parsley, hazelnuts, mitsukan sauce with ginger',
    UnitPrice: 13.5,
    SmallImagePath: './images/goods/small/14',
    BigImagePath: './images/goods/big/14',
  },
  {
    ProductID: 31,
    ProductType: 'food',
    ProductName: 'Hummus',
    ProductWeight: '180/85 g',
    isSpicy: false,
    isVegetarian: true,
    ProductDescription:
      'Hummus with baked pepper and eggplant: hummus, focaccia, pepper, eggplant',
    UnitPrice: 10.3,
    SmallImagePath: './images/goods/small/15',
    BigImagePath: './images/goods/big/15',
  },
];
